# Generated by Django 2.2.16 on 2020-10-07 06:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('ID', models.AutoField(primary_key=True, serialize=False)),
                ('ADDRESS', models.CharField(blank=True, max_length=500)),
                ('EMAIL_ID', models.EmailField(max_length=256)),
                ('PASSWORD', models.CharField(blank=True, max_length=256)),
                ('DEVICE_ID', models.CharField(max_length=256)),
                ('LATITUDE', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('LONGITUDE', models.DecimalField(decimal_places=6, max_digits=9, null=True)),
                ('CREATED_DATE', models.DateField(auto_now_add=True)),
                ('MODIFIED_DATE', models.DateField(auto_now=True)),
                ('IsActive', models.BooleanField(default=True)),
                ('IsLogout', models.BooleanField(default=True)),
            ],
        ),
        migrations.CreateModel(
            name='Prescriptions',
            fields=[
                ('Image_ID', models.AutoField(primary_key=True, serialize=False)),
                ('Image_Name', models.CharField(max_length=1000)),
                ('Image_URL', models.ImageField(upload_to='images/')),
                ('DEVICE_ID', models.CharField(max_length=255)),
                ('IMAGE_UPLOAD_DATE', models.DateField(auto_now_add=True)),
                ('IMAGE_UPLOAD_TIME', models.TimeField(auto_now_add=True)),
                ('CREATED_DATE', models.DateField(auto_now_add=True)),
                ('MODIFIED_DATE', models.DateField(auto_now=True)),
                ('USER_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrescriptionDashboard.User')),
            ],
        ),
    ]
