# Generated by Django 2.2.16 on 2020-10-07 07:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrescriptionDashboard', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptions',
            name='IMAGE_UPLOAD_DATE',
            field=models.DateField(),
        ),
        migrations.AlterField(
            model_name='prescriptions',
            name='IMAGE_UPLOAD_TIME',
            field=models.TimeField(),
        ),
    ]
