# Generated by Django 2.2.16 on 2020-10-08 15:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrescriptionDashboard', '0002_auto_20201007_1309'),
    ]

    operations = [
        migrations.AlterField(
            model_name='prescriptions',
            name='Image_Name',
            field=models.CharField(max_length=255),
        ),
    ]
