# Generated by Django 2.2.16 on 2020-10-12 11:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrescriptionDashboard', '0003_auto_20201008_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='IsLogout',
            field=models.BooleanField(default=False),
        ),
    ]
