# Generated by Django 2.2.16 on 2020-11-11 07:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('PrescriptionDashboard', '0004_auto_20201012_1729'),
    ]

    operations = [
        migrations.CreateModel(
            name='DrugDetails',
            fields=[
                ('DRUG_ID', models.AutoField(primary_key=True, serialize=False)),
                ('DRUG_NAME', models.CharField(max_length=100)),
                ('DRUG_REQ_QTY', models.IntegerField()),
                ('DRUG_INSTOCK', models.IntegerField()),
                ('ISFULLFILL', models.BooleanField()),
                ('PRESCRIPTION_ID', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='PrescriptionDashboard.Prescriptions')),
            ],
        ),
    ]
