# Generated by Django 2.2.16 on 2020-11-17 09:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrescriptionDashboard', '0005_drugdetails'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='BRANCH_CODE',
            field=models.IntegerField(default=601),
        ),
        migrations.AddField(
            model_name='user',
            name='USERNAME',
            field=models.CharField(default='test', max_length=256),
        ),
    ]
