# Generated by Django 2.2.16 on 2020-11-17 10:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrescriptionDashboard', '0006_auto_20201117_1440'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='BRANCH_CODE',
            new_name='BRANCHCODE',
        ),
    ]
