# Generated by Django 2.2.16 on 2020-11-21 11:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('PrescriptionDashboard', '0007_auto_20201117_1552'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drugdetails',
            name='DRUG_INSTOCK',
            field=models.IntegerField(null=True),
        ),
        migrations.AlterField(
            model_name='drugdetails',
            name='ISFULLFILL',
            field=models.BooleanField(null=True),
        ),
    ]
