# Generated by Django 2.2.16 on 2020-12-10 19:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrescriptionDashboard', '0008_auto_20201121_1724'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='EMAIL_ID',
            new_name='EMAIL_id',
        ),
    ]
