# Generated by Django 2.2.16 on 2020-12-10 19:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('PrescriptionDashboard', '0009_auto_20201211_0059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='EMAIL_id',
            new_name='EMAIL_ID',
        ),
    ]
